### ISSUE TITLE
Add a License to project

### ISSUE THREAD

**Issue by JaseemVillan** [JaseemVillan/github-projects-playground#3]
Hey @Athul0008 ,I wonder what type of license I should add to this project.

**Comment by Athul0008** [comment]
> I wonder what type of license I should use.

use driving license

**Comment by JaseemVillan** [comment]
you are so funny

**Comment by Athul0008** [comment]
> Hey @Athul0008 ,I wonder what type of license I should add to this project.

i don't give a f**k

**Comment by Athul0008** [comment]
Sorry , Go with MIT license

**Comment by JaseemVillan** [comment]
Okay, thank you for the reply

**Comment by JaseemVillan** [comment]
Thanks @Athul0008 , you're the best. I added the LICENSE file.
